# Generated by Django 4.2 on 2025-03-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offdayapp", "0004_leave_delete_history"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offday",
            name="date_added",
        ),
        migrations.AddField(
            model_name="offday",
            name="type",
            field=models.CharField(
                choices=[("off", "Off"), ("leave", "Leave")],
                default="off",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="Leave",
        ),
    ]
